version: "3.3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      SERVER_NAME: "Our Minecraft Server"
      MOTD: "First Peaceful World"
      DIFFICULTY: "normal"
      MEMORY: 3G
    volumes:
      - ./minecraft-data:/data
      - ./saves-to-import:/worlds:ro

  backups:
    image: itzg/mc-backup
    depends_on:
      - mc
    environment:
      BACKUP_INTERVAL: "2h"
    volumes:
      - ./minecraft-data:/data:ro
      - ./mc-backups:/backups:rw
    network_mode: "service:mc"

  overviewer:
    image: mide/minecraft-overviewer:latest
    depends_on:
      - mc
    environment:
      - CONFIG_PATH=/config/overviewer_config.py
      - CRON_SCHEDULE=0 */12 * * *
      - MINECRAFT_VERSION=latest
    volumes:
      - ./minecraft-data/world:/home/minecraft/server/world:ro
      - ./overviewer-data:/home/minecraft/render/:rw 
      - ./data/overview/overviewer_config.py:/config/overviewer_config.py:ro
    restart: on-failure:5

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./overviewer-data:/usr/share/nginx/html:ro
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
